name: Build SocksTun APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout con Submodulos
        uses: actions/checkout@v4
        with:
          submodules: 'recursive' # ESTO ES LO QUE BAJA EL TRADUCTOR
          fetch-depth: 0

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Permisos para Gradle
        run: chmod +x gradlew

      - name: Compilar APK (Debug)
        run: ./gradlew assembleDebug

      - name: Subir APK Resultante
        uses: actions/upload-artifact@v4
        with:
          name: MiAppTunel-Base
          path: app/build/outputs/apk/debug/*.apk
